name: "nix-build --arg cudaSupport true"
on:
  pull_request:
  push:
    branches:
      - master
      - unfree
  schedule:
    - cron:  '50 6 * * *'
  workflow_dispatch:
jobs:
  nix-build:
    strategy:
      fail-fast: false
      matrix:
        nurRepo:
          - some-pkgs
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - name: Consume the read-only free cachix
      uses: cachix/cachix-action@v13
      with:
        name: some-unfree
    - name: Consume read-only cuda-maintainers cachix
      uses: cachix/cachix-action@v13
      with:
        name: cuda-maintainers
    - name: Setup writeable unfree cachix
      uses: cachix/cachix-action@v13
      with:
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN_UNFREE }}'
        name: some-unfree
    - name: Build some-pkgs
      run: nix run github:Mic92/nix-fast-build -- --skip-cached --no-nom --flake ".#legacyPackages.$(nix eval --raw --impure --expr builtins.currentSystem).pkgsCuda.some-pkgs"
    - name: Build some-pkgs-py
      run: nix run github:Mic92/nix-fast-build -- --skip-cached --no-nom --flake ".#legacyPackages.$(nix eval --raw --impure --expr builtins.currentSystem).pkgsCuda.some-pkgs-py"
    - name: Trigger NUR update
      # Don't replace <YOUR_REPO_NAME> here!
      if: ${{ matrix.nurRepo != '<YOUR_REPO_NAME>' }}
      run: curl -XPOST "https://nur-update.nix-community.org/update?repo=${{ matrix.nurRepo }}"
