name: "Rebase the unfree branch on master"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  rebase-unfree:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: configure git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - run: ./update-unfree-branch.sh
