name: "nix-update all outputs"
on:
  schedule:
    - cron:  '10 5 * * *'
  workflow_dispatch:
jobs:
  nix-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install nix
      uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
        install_url: https://releases.nixos.org/nix/nix-2.9.1/install
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - name: Show nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - name: Setup cachix
      uses: cachix/cachix-action@v12
      with:
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        name: pkgs
    - run: git config --global user.email "github-action@users.noreply.github.com"
    - run: git config --global user.name "github-action"
    - name: nix-update
      run: nix run .#update-flake-outputs -- --remote origin ./.
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
