name: "nix-update"
on:
  schedule:
    - cron:  '10 5 * * *'
  workflow_dispatch:
jobs:
  nix-update:
    runs-on: ubuntu-latest
    environment: GH_PAT
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        token: ${{ secrets.GH_PAT }}
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v16
      with:
        github-token: ${{ secrets.GH_PAT }}
    - uses: DeterminateSystems/magic-nix-cache-action@v9
    - name: Show nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - name: Setup cachix
      uses: cachix/cachix-action@v16
      with:
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        name: pkgs
    - run: git config --global user.email "github-action@users.noreply.github.com"
    - run: git config --global user.name "github-action"
    - name: nix-update
      run: nix run .#update-flake-outputs -- --remote origin --overwrite-existing ./.
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
