name: "nix-update all outputs"
on:
  schedule:
    - cron:  '10 5 * * *'
  workflow_dispatch:
jobs:
  nix-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install nix
      uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
        install_url: https://releases.nixos.org/nix/nix-2.9.1/install
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - name: Show nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - name: Setup cachix
      # Don't replace <YOUR_CACHIX_NAME> here!
      if: ${{ matrix.cachixName != '<YOUR_CACHIX_NAME>' }}
      uses: cachix/cachix-action@v12
      with:
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        name: ${{ matrix.cachixName }}
    - name: Check evaluation
      run: |
        nix-env -f . -qa \* --meta --xml \
          --allowed-uris https://static.rust-lang.org \
          --option restrict-eval true \
          --option allow-import-from-derivation true \
          --drv-path --show-trace \
          -I nixpkgs=$(nix-instantiate --find-file nixpkgs) \
          -I $PWD
    - name: nix-update
      run: nix run .#update-flake-outputs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
